### ISSUE TITLE
发现一个搜索的问题

### ISSUE THREAD

**Issue by huiyadanli** [Kengxxiao/Kyouka#16]
### 浏览器
Chrome 84.0.4147.105

### 复现步骤：
进入网站 -> 输入公会名搜索 -> 有结果 （正常）

然后点击历史数据 -> 切换时间
![image](https://user-images.githubusercontent.com/15783049/88875935-c3115400-d254-11ea-94e1-42e6f03ecb2a.png)

再点击查询，返回的是前10的结果，点击重置历史查询器也是一样的结果

![image](https://user-images.githubusercontent.com/15783049/88876082-1edbdd00-d255-11ea-98a1-f919d1e9c893.png)

F12 看了下请求，请求中没有工会名称。

应该存粹是页面的问题，麻烦看下。

实际多次搜索中会有更多问题，这个能够稳定复现

**Comment by Kengxxiao** [comment]
已修复
