### ISSUE TITLE
能否提供网站查询的api

### ISSUE THREAD

**Issue by genres17** [Kengxxiao/Kyouka#19]
您好，公会战实时排名这个数据其实还是很重要的，网页这种形式毕竟查询起来还是比较麻烦，目前想转载数据，只能用爬虫来爬，还得考虑各种冷却限制，与其这样很麻烦，不如给出相关查询api和授权token，这样大家都方便，谢谢

**Comment by Kengxxiao** [comment]
谢谢，不过这个只是我个人一时兴起做的，在不超过预算的情况下不打算经常维护，所以没有这方面的想法，获取数据可以考虑直接使用js里的api调用

**Comment by genres17** [comment]
> 
> 
> 谢谢，不过这个只是我个人一时兴起做的，在不超过预算的情况下不打算经常维护，所以没有这方面的想法，获取数据可以考虑直接使用js里的api调用

嘿嘿，已经实现了全部功能
