### ISSUE TITLE
请问如何查看/删除全部收藏

### ISSUE THREAD

**Issue by Hieuzest** [Kengxxiao/Kyouka#27]
一些收藏是在过去的某些时候添加的，在当期中无法找到该行会，但仍占用收藏数量。请问如何删除这些收藏项。

**Comment by Kengxxiao** [comment]
使用手机浏览器请直接清除网站缓存
PC上可以进行如下操作：
F12 打开控制台 -> 应用程序(Application) -> 本地存储(Local Storage) -> 找到名为fav的密钥(key)，将其直接删除或根据JSON格式修改内部的数据文本
