### ISSUE TITLE
提示{'message': 'Endpoint IP address is not allowed'}

### ISSUE THREAD

**Issue by hzx1987227** [Kengxxiao/Kyouka#3]
您好,

调用您的API提示{'message': 'Endpoint IP address is not allowed'}

请问是否能解除限制或提供更完善的api制度,以免被滥用

谢谢

**Comment by Kengxxiao** [comment]
因为你一直在请求/name/-1 能不能跟我说说你在干什么

**Comment by hzx1987227** [comment]
https://i.imgur.com/YyKg2Zi.png

某群的码直接拿来用了.

被限制后查看了您前端的请求发现是0,已修改

**Comment by Kengxxiao** [comment]
查询自己公会的信息请使用/fav接口
已解除限制

**Comment by hzx1987227** [comment]
感谢
