### ISSUE TITLE
关于数据来源

### ISSUE THREAD

**Issue by Ai-Himmel** [Kengxxiao/Kyouka#7]
是对`clan_battle/period_ranking`的一个wrapper吗？

**Comment by Kengxxiao** [comment]
更新部分是
网站后端是自己写的数据处理部分

**Comment by Ai-Himmel** [comment]
辛苦了
话说cy这套通信系统从cgss到szb到pcr一如既往的沙雕（
我还想自己写一个的，有大佬做了我就坐享其成了（

**Comment by Kengxxiao** [comment]
好的，感谢前辈支持(*￣▽￣*)
